CREATE ROLE gerente;

GRANT SELECT,INSERT,UPDATE,DELETE ON fitas TO gerente;
GRANT SELECT,INSERT,UPDATE,DELETE ON filmes TO gerente;
GRANT SELECT,INSERT,UPDATE,DELETE ON filmes_has_categorias TO gerente;
GRANT SELECT,INSERT,UPDATE,DELETE ON estrelatos TO gerente;
GRANT SELECT,INSERT,UPDATE,DELETE ON atores TO gerente;
