-- MySQL Script generated by MySQL Workbench
-- Sun 11 Nov 2018 11:26:21 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8 ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`cliente` (
  `numAssociado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `CEP` INT NOT NULL,
  PRIMARY KEY (`numAssociado`),
  UNIQUE INDEX `numAssociado_UNIQUE` (`numAssociado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `identificador` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `duracaoLocacao` INT NOT NULL,
  PRIMARY KEY (`identificador`),
  UNIQUE INDEX `identificador_UNIQUE` (`identificador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`fita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`fita` (
  `numero` INT NOT NULL,
  `filme_identificador` INT NOT NULL,
  `fita_numero` INT NULL,
  `disponibilidade` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_fita_filme1_idx` (`filme_identificador` ASC),
  INDEX `fk_fita_fita1_idx` (`fita_numero` ASC),
  CONSTRAINT `fk_fita_filme1`
    FOREIGN KEY (`filme_identificador`)
    REFERENCES `locadora`.`filme` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fita_fita1`
    FOREIGN KEY (`fita_numero`)
    REFERENCES `locadora`.`fita` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`emprestimo` (
  `instanteLocacao` INT NOT NULL,
  `cliente_numAssociado` INT NOT NULL,
  `fita_numero` INT NOT NULL,
  `dataAluguel` DATE NOT NULL,
  `preco` INT NOT NULL,
  PRIMARY KEY (`instanteLocacao`),
  UNIQUE INDEX `instanteLocacao_UNIQUE` (`instanteLocacao` ASC),
  INDEX `fk_emprestimo_cliente1_idx` (`cliente_numAssociado` ASC),
  INDEX `fk_emprestimo_fita1_idx` (`fita_numero` ASC),
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`cliente_numAssociado`)
    REFERENCES `locadora`.`cliente` (`numAssociado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_fita1`
    FOREIGN KEY (`fita_numero`)
    REFERENCES `locadora`.`fita` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`telefone` (
  `cliente_numAssociado` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`cliente_numAssociado`, `numero`),
  CONSTRAINT `fk_telefone_cliente`
    FOREIGN KEY (`cliente_numAssociado`)
    REFERENCES `locadora`.`cliente` (`numAssociado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`ator` (
  `identificador` INT NOT NULL,
  `nomeReal` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(45) NULL,
  PRIMARY KEY (`identificador`),
  UNIQUE INDEX `identificador_UNIQUE` (`identificador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`estrelato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`estrelato` (
  `filme_identificador` INT NOT NULL,
  `ator_identificador` INT NOT NULL,
  PRIMARY KEY (`filme_identificador`, `ator_identificador`),
  INDEX `fk_estrelato_ator1_idx` (`ator_identificador` ASC),
  CONSTRAINT `fk_estrelato_filme1`
    FOREIGN KEY (`filme_identificador`)
    REFERENCES `locadora`.`filme` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estrelato_ator1`
    FOREIGN KEY (`ator_identificador`)
    REFERENCES `locadora`.`ator` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`categoria` (
  `identificador` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identificador`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `identificador_UNIQUE` (`identificador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`filme_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme_has_categoria` (
  `filme_identificador` INT NOT NULL,
  `categoria_identificador` INT NOT NULL,
  PRIMARY KEY (`filme_identificador`, `categoria_identificador`),
  INDEX `fk_filme_has_categoria_categoria1_idx` (`categoria_identificador` ASC),
  INDEX `fk_filme_has_categoria_filme1_idx` (`filme_identificador` ASC),
  CONSTRAINT `fk_filme_has_categoria_filme1`
    FOREIGN KEY (`filme_identificador`)
    REFERENCES `locadora`.`filme` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_categoria_categoria1`
    FOREIGN KEY (`categoria_identificador`)
    REFERENCES `locadora`.`categoria` (`identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
