-- MySQL Script generated by MySQL Workbench
-- Sun 18 Nov 2018 10:14:18 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema congresso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema congresso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `congresso` DEFAULT CHARACTER SET utf8 ;
USE `congresso` ;

-- -----------------------------------------------------
-- Table `congresso`.`participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`participantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `numero_fax` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idparticipante_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`congressos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`congressos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `dataRealizacao` DATE NOT NULL,
  `editora` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`sessoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`sessoes` (
  `timestamp` INT NOT NULL,
  `congresso_codigo` INT NOT NULL,
  `horario` VARCHAR(45) NULL,
  `moderador_cpf` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `congresso_codigo`),
  INDEX `fk_sessao_congresso1_idx` (`congresso_codigo` ASC),
  INDEX `fk_sessao_participante1_idx` (`moderador_cpf` ASC),
  CONSTRAINT `fk_sessao_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessao_participante1`
    FOREIGN KEY (`moderador_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`artigos` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `sessao_timestamp` INT NOT NULL,
  `sessao_congresso_codigo` INT NOT NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_artigo_sessao1_idx` (`sessao_timestamp` ASC, `sessao_congresso_codigo` ASC),
  CONSTRAINT `fk_artigo_sessao1`
    FOREIGN KEY (`sessao_timestamp` , `sessao_congresso_codigo`)
    REFERENCES `congresso`.`sessoes` (`timestamp` , `congresso_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`autores` (
  `participante_cpf` INT NOT NULL,
  `congresso_codigo` INT NOT NULL,
  `artigo_numero` INT NOT NULL,
  PRIMARY KEY (`participante_cpf`, `congresso_codigo`),
  INDEX `fk_autor_congresso1_idx` (`congresso_codigo` ASC),
  INDEX `fk_autor_artigo1_idx` (`artigo_numero` ASC),
  CONSTRAINT `fk_autor_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_artigo1`
    FOREIGN KEY (`artigo_numero`)
    REFERENCES `congresso`.`artigos` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`telefones` (
  `participante_id` INT NOT NULL,
  `numero` INT(9) NOT NULL,
  PRIMARY KEY (`participante_id`),
  CONSTRAINT `fk_telefone_participante1`
    FOREIGN KEY (`participante_id`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`corpoAvaliadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`corpoAvaliadores` (
  `congresso_codigo` INT NOT NULL,
  PRIMARY KEY (`congresso_codigo`),
  CONSTRAINT `fk_corpoAvaliadores_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`opinioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`opinioes` (
  `artigo_numero` INT NOT NULL,
  `resumoOpniao` VARCHAR(275) NULL,
  `corpoAvaliadores_congresso_codigo` INT NOT NULL,
  PRIMARY KEY (`artigo_numero`, `corpoAvaliadores_congresso_codigo`),
  INDEX `fk_opiniao_artigo1_idx` (`artigo_numero` ASC),
  INDEX `fk_opiniao_corpoAvaliadores1_idx` (`corpoAvaliadores_congresso_codigo` ASC),
  CONSTRAINT `fk_opiniao_artigo1`
    FOREIGN KEY (`artigo_numero`)
    REFERENCES `congresso`.`artigos` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opiniao_corpoAvaliadores1`
    FOREIGN KEY (`corpoAvaliadores_congresso_codigo`)
    REFERENCES `congresso`.`corpoAvaliadores` (`congresso_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`membrosComitePrograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`membrosComitePrograma` (
  `congresso_codigo1` INT NOT NULL,
  `participante_cpf` INT NOT NULL,
  PRIMARY KEY (`congresso_codigo1`, `participante_cpf`),
  INDEX `fk_comitePrograma_congresso1_idx` (`congresso_codigo1` ASC),
  INDEX `fk_comitePrograma_participante1_idx` (`participante_cpf` ASC),
  CONSTRAINT `fk_comitePrograma_congresso1`
    FOREIGN KEY (`congresso_codigo1`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comitePrograma_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`membrosComiteOrganizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`membrosComiteOrganizador` (
  `congresso_codigo` INT NOT NULL,
  `participante_cpf` INT NOT NULL,
  PRIMARY KEY (`congresso_codigo`, `participante_cpf`),
  INDEX `fk_integraComiteOrganizador_congresso1_idx` (`congresso_codigo` ASC),
  INDEX `fk_integraComiteOrganizador_participante1_idx` (`participante_cpf` ASC),
  CONSTRAINT `fk_integraComiteOrganizador_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integraComiteOrganizador_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`gruposTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`gruposTrabalho` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`membrosGrupoTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`membrosGrupoTrabalho` (
  `grupoTrabalho_codigo` INT NOT NULL,
  `participante_cpf` INT NOT NULL,
  PRIMARY KEY (`grupoTrabalho_codigo`, `participante_cpf`),
  INDEX `fk_grupoTrabalho_membro_grupoTrabalho1_idx` (`grupoTrabalho_codigo` ASC),
  INDEX `fk_grupoTrabalho_membro_participante1_idx` (`participante_cpf` ASC),
  CONSTRAINT `fk_grupoTrabalho_membro_grupoTrabalho1`
    FOREIGN KEY (`grupoTrabalho_codigo`)
    REFERENCES `congresso`.`gruposTrabalho` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupoTrabalho_membro_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`gruposTrabalho_congressos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`gruposTrabalho_congressos` (
  `grupoTrabalho_codigo` INT NOT NULL,
  `congresso_codigo` INT NOT NULL,
  PRIMARY KEY (`grupoTrabalho_codigo`, `congresso_codigo`),
  INDEX `fk_grupoTrabalho_congresso_congresso1_idx` (`congresso_codigo` ASC),
  CONSTRAINT `fk_grupoTrabalho_congresso_grupoTrabalho1`
    FOREIGN KEY (`grupoTrabalho_codigo`)
    REFERENCES `congresso`.`gruposTrabalho` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupoTrabalho_congresso_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`membroCorpoDeAvaliadoresCongresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`membroCorpoDeAvaliadoresCongresso` (
  `participante_cpf` INT NOT NULL,
  `corpoAvaliadores_congresso_codigo` INT NOT NULL,
  PRIMARY KEY (`participante_cpf`, `corpoAvaliadores_congresso_codigo`),
  INDEX `fk_corpoDeAvaliadores_avaliador_participante1_idx` (`participante_cpf` ASC),
  INDEX `fk_membroCorpoDeAvaliadoresCongresso_corpoAvaliadores1_idx` (`corpoAvaliadores_congresso_codigo` ASC),
  CONSTRAINT `fk_corpoDeAvaliadores_avaliador_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membroCorpoDeAvaliadoresCongresso_corpoAvaliadores1`
    FOREIGN KEY (`corpoAvaliadores_congresso_codigo`)
    REFERENCES `congresso`.`corpoAvaliadores` (`congresso_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`convidados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`convidados` (
  `congresso_codigo` INT NOT NULL,
  `participante_id` INT NOT NULL,
  PRIMARY KEY (`congresso_codigo`, `participante_id`),
  INDEX `fk_convidados_participante1_idx` (`participante_id` ASC),
  CONSTRAINT `fk_convidados_congresso1`
    FOREIGN KEY (`congresso_codigo`)
    REFERENCES `congresso`.`congressos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convidados_participante1`
    FOREIGN KEY (`participante_id`)
    REFERENCES `congresso`.`participantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `congresso`.`julgamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congresso`.`julgamentos` (
  `artigo_numero` INT NOT NULL,
  `aceito` VARCHAR(45) NULL,
  PRIMARY KEY (`artigo_numero`),
  CONSTRAINT `fk_julgamento_artigo1`
    FOREIGN KEY (`artigo_numero`)
    REFERENCES `congresso`.`artigos` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
